<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SecureExchanges.NetCore" Version="26.6.25.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SESARWebHook.Core.NetCore\SESARWebHook.Core.NetCore.csproj" />
    <ProjectReference Include="..\SESARWebHook.SESARLightUtils\SESARWebHook.SESARLightUtils.csproj" />
  </ItemGroup>

</Project>
